### ISSUE TITLE
small features design

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/Project2_badsmell#3]
===Issue related================================================
- [x] 1. Total number of issues
- [x] 5. Number of issues without comments
- [x] 6. Number of issues each week

===Label related================================================
- [x] 2. Number of labels
- [x] 4. Number of times each label was used
- [x] 7. Mean and standard deviation of times spent in each issue
- [x] 8. "Unusually long" time; i.e. more than, say, mean + 1.5 or 2 standard deviations time in a issue
- [x] 15. Mean and standard deviation number of labels assigned to each issue

===Mixed features related================================================
- [x] 3.  Number of times each milestone was used
- [x] 9. Percentage of issues using labels
- [x] 10. Percentage of issues using milestones
- [x] 11. Percentage of issues using assignees

===User related================================================
- [x] 12. "Unusually small or large" number of issues handled by one person(<10%)
- [x] 16.Issue participating times of each user

**Comment by dragonfly90** [comment]
Ok

**Comment by Winbobob** [comment]
1~9 @dragonfly90 
10~16 @Winbobob
